name: f1_app
description: "Formula 1 tesz app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  http: ^1.2.2
  flutter_emoji: ^2.5.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0




flutter:

  uses-material-design: true

  assets:
#    - .env
    - assets/config.json


